language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'
  
os:
  - linux
  - osx

install:
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        which python || travis_retry brew install python && brew link --overwrite python
        which python
        python --version
    fi
                  
  - python setup.py install

script:
  - python -c "import genesis"
  - python -c "import genesis; print(genesis.__version__)"

notifications:
  email:
    recipients:
      - manodeep@gmail.com
    on_success: change
    on_failure: always
  
